### ISSUE TITLE
Be able to add multiple criteria per submit

### ISSUE THREAD

**Issue by cmilhaupt** [cmilhaupt/audition-web-form#1]
Add a button that says "new entry" that duplicates the "criteria" and "change" sections beneath the old one and above the submit button. Then do a another "insert" statement for each new field added in the php script.

**Comment by cmilhaupt** [comment]
This may be helpful
http://jsfiddle.net/2t9Dh/554/

**Comment by VinMags16** [comment]
I'd say this is probably the issue we should cover last.  This is more a quality of life change than functionality.

**Comment by VinMags16** [comment]
If you're gonna tackle the back end issue I'll take this one

**Comment by cmilhaupt** [comment]
Fixed the front end of this so the "criteria" through "comments" sections are duplicated with unique names and ids so they can be grabbed independently from the php script.

**Comment by VinMags16** [comment]
I have code for the fix, waiting on DB access or some work around to start testing.
