### ISSUE TITLE
Create option/default to deleting database every night

### ISSUE THREAD

**Issue by VinMags16** [cmilhaupt/audition-web-form#20]
With our current implementation we would need to clear the database every night to make way for new data, so we need to setup some sort of script to remove all data from the database at like 3 or 4 am every night so we don't have to remember to reset it.

**Comment by cmilhaupt** [comment]
The date is already added to each entry to I don't see why we have to delete it when we can sort and filter by date. Are you worried about space?

**Comment by VinMags16** [comment]
No I just didn't know we had the date being sent with it.  Regardless we'll need to add it to the firebase version or whatever version we decide on after this band camp

**Comment by VinMags16** [comment]
Decided to leave dates to filter and use in graphs.  Now irrelevant, closing
