### ISSUE TITLE
Icon for the site is still the Angular logo

### ISSUE THREAD

**Issue by VinMags16** [cmilhaupt/audition-web-form#33]
Needs changed to Purdue P or something like that.

**Comment by cmilhaupt** [comment]
<img width="32" alt="block p 64x64" src="https://user-images.githubusercontent.com/15024866/31048099-7ed394be-a5e4-11e7-8bec-ec7c00fd1420.png">

**Comment by VinMags16** [comment]
Finished by @JakeHarris12 .  Closing issue
